name: sanjeevini
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ^3.6.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13
  geolocator: ^9.0.2
  fluttertoast: ^8.0.9
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true